import { Tile } from "../types/board";

export const JAIL_INDEX = 10;
export const GO_INDEX = 0;
export const GO_TO_JAIL_INDEX = 30;

export const BOARD: Tile[] = [
  { tileIndex: 0, type: "GO" },

  // TODO: Remove the airport having multiple houses and put real prices
  // Dark Purple – Terai Cities
  {
    tileIndex: 1,
    type: "PROPERTY",
    id: "janakpur",
    name: "Janakpur",
    price: 60,
    baseRent: 2,
    houseRent: [10, 30, 90, 160],
    hotelRent: 250,
    houseBuildCost: 12,
    group: "terai",
  },
  { tileIndex: 2, type: "COMMUNITY_CHEST" },
  {
    tileIndex: 3,
    type: "PROPERTY",
    id: "birgunj",
    name: "Birgunj",
    price: 60,
    baseRent: 4,
    houseRent: [20, 60, 180, 320],
    hotelRent: 450,
    houseBuildCost: 12,
    group: "terai",
  },
  { tileIndex: 4, type: "TAX", amount: 200 },

  // Rail
  {
    tileIndex: 5,
    type: "PROPERTY",
    id: "south_airport",
    name: "South airport",
    price: 200,
    baseRent: 25,
    houseBuildCost: 40,
    group: "airport",
    houseRent: [20, 60, 180, 320],
    hotelRent: 450,
  },

  // Light Blue – Lakes
  {
    tileIndex: 6,
    type: "PROPERTY",
    id: "phewa",
    name: "Phewa Lake",
    price: 100,
    baseRent: 6,
    houseRent: [30, 90, 270, 400],
    hotelRent: 550,
    houseBuildCost: 20,
    group: "lake",
  },
  { tileIndex: 7, type: "CHANCE" },
  {
    tileIndex: 8,
    type: "PROPERTY",
    id: "rara",
    name: "Rara Lake",
    price: 100,
    baseRent: 8,
    houseRent: [40, 100, 300, 450],
    hotelRent: 600,
    houseBuildCost: 20,
    group: "lake",
  },
  {
    tileIndex: 9,
    type: "PROPERTY",
    id: "begnas",
    name: "Begnas Lake",
    price: 120,
    baseRent: 10,
    houseRent: [50, 150, 450, 625],
    hotelRent: 750,
    houseBuildCost: 24,
    group: "lake",
  },

  { tileIndex: 10, type: "JAIL" },

  // Pink – Temples
  {
    tileIndex: 11,
    type: "PROPERTY",
    id: "pashupati",
    name: "Pashupati",
    price: 140,
    baseRent: 12,
    houseRent: [60, 180, 500, 700],
    hotelRent: 900,
    houseBuildCost: 28,
    group: "temple",
  },
  {
    tileIndex: 12,
    type: "PROPERTY",
    id: "hydropower",
    name: "Hydropower",
    price: 150,
    baseRent: 4,
    houseBuildCost: 30,
    group: "utility",
    houseRent: [20, 60, 180, 320],
    hotelRent: 450,
  },
  {
    tileIndex: 13,
    type: "PROPERTY",
    id: "boudha",
    name: "Boudha",
    price: 140,
    baseRent: 14,
    houseRent: [70, 200, 550, 750],
    hotelRent: 950,
    houseBuildCost: 28,
    group: "temple",
  },
  {
    tileIndex: 14,
    type: "PROPERTY",
    id: "swayambhu",
    name: "Swayambhu",
    price: 160,
    baseRent: 16,
    houseRent: [80, 220, 600, 800],
    hotelRent: 1000,
    houseBuildCost: 32,
    group: "temple",
  },

  // Rail
  {
    tileIndex: 15,
    type: "PROPERTY",
    id: "east_airport",
    name: "East airport",
    price: 200,
    baseRent: 25,
    houseBuildCost: 40,
    group: "airport",
    houseRent: [20, 60, 180, 320],
    hotelRent: 450,
  },

  // Orange – National Parks
  {
    tileIndex: 16,
    type: "PROPERTY",
    id: "chitwan",
    name: "Chitwan",
    price: 180,
    baseRent: 18,
    houseRent: [90, 250, 700, 875],
    hotelRent: 1050,
    houseBuildCost: 36,
    group: "national_park",
  },
  { tileIndex: 17, type: "COMMUNITY_CHEST" },
  {
    tileIndex: 18,
    type: "PROPERTY",
    id: "bardia",
    name: "Bardia",
    price: 180,
    baseRent: 20,
    houseRent: [100, 300, 750, 925],
    hotelRent: 1100,
    houseBuildCost: 36,
    group: "national_park",
  },
  {
    tileIndex: 19,
    type: "PROPERTY",
    id: "koshi_tappu",
    name: "Koshi Tappu",
    price: 200,
    baseRent: 22,
    houseRent: [110, 330, 800, 975],
    hotelRent: 1150,
    houseBuildCost: 40,
    group: "national_park",
  },

  { tileIndex: 20, type: "FREE_PARKING" },

  // Red – Valley Cities
  {
    tileIndex: 21,
    type: "PROPERTY",
    id: "kathmandu",
    name: "Kathmandu",
    price: 220,
    baseRent: 24,
    houseRent: [120, 360, 850, 1025],
    hotelRent: 1200,
    houseBuildCost: 44,
    group: "valley",
  },
  { tileIndex: 22, type: "CHANCE" },
  {
    tileIndex: 23,
    type: "PROPERTY",
    id: "pokhara",
    name: "Pokhara",
    price: 220,
    baseRent: 26,
    houseRent: [130, 390, 900, 1100],
    hotelRent: 1275,
    houseBuildCost: 44,
    group: "valley",
  },
  {
    tileIndex: 24,
    type: "PROPERTY",
    id: "patan",
    name: "Patan",
    price: 240,
    baseRent: 28,
    houseRent: [140, 400, 950, 1150],
    hotelRent: 1350,
    houseBuildCost: 48,
    group: "valley",
  },

  // Rail
  {
    tileIndex: 25,
    type: "PROPERTY",
    id: "west_airport",
    name: "West airport",
    price: 200,
    baseRent: 25,
    houseBuildCost: 40,
    group: "airport",
    houseRent: [20, 60, 180, 320],
    hotelRent: 450,
  },

  // Yellow – Viewpoints
  {
    tileIndex: 26,
    type: "PROPERTY",
    id: "nagarkot",
    name: "Nagarkot",
    price: 260,
    baseRent: 32,
    houseRent: [160, 500, 1100, 1300],
    hotelRent: 1500,
    houseBuildCost: 52,
    group: "viewpoint",
  },
  {
    tileIndex: 27,
    type: "PROPERTY",
    id: "sarangkot",
    name: "Sarangkot",
    price: 260,
    baseRent: 34,
    houseRent: [170, 520, 1150, 1350],
    hotelRent: 1550,
    houseBuildCost: 52,
    group: "viewpoint",
  },
  {
    tileIndex: 28,
    type: "PROPERTY",
    id: "telecom",
    name: "Telecom",
    price: 150,
    baseRent: 4,
    houseBuildCost: 30,
    group: "utility",
    houseRent: [20, 60, 180, 320],
    hotelRent: 450,
  },
  {
    tileIndex: 29,
    type: "PROPERTY",
    id: "dhulikhel",
    name: "Dhulikhel",
    price: 280,
    baseRent: 36,
    houseRent: [180, 540, 1200, 1400],
    hotelRent: 1600,
    houseBuildCost: 56,
    group: "viewpoint",
  },

  { tileIndex: 30, type: "GO_TO_JAIL" },

  // Green – Mountains
  {
    tileIndex: 31,
    type: "PROPERTY",
    id: "annapurna",
    name: "Annapurna",
    price: 300,
    baseRent: 26,
    houseRent: [130, 390, 900, 1100],
    hotelRent: 1275,
    houseBuildCost: 60,
    group: "mountain",
  },
  {
    tileIndex: 32,
    type: "PROPERTY",
    id: "langtang",
    name: "Langtang",
    price: 300,
    baseRent: 26,
    houseRent: [130, 390, 900, 1100],
    hotelRent: 1275,
    houseBuildCost: 60,
    group: "mountain",
  },
  { tileIndex: 33, type: "COMMUNITY_CHEST" },
  {
    tileIndex: 34,
    type: "PROPERTY",
    id: "manaslu",
    name: "Manaslu",
    price: 320,
    baseRent: 28,
    houseRent: [150, 450, 1000, 1200],
    hotelRent: 1400,
    houseBuildCost: 64,
    group: "mountain",
  },

  // Rail
  {
    tileIndex: 35,
    type: "PROPERTY",
    id: "north_airport",
    name: "North airport",
    price: 200,
    baseRent: 25,
    houseBuildCost: 40,
    group: "airport",
    houseRent: [20, 60, 180, 320],
    hotelRent: 450,
  },

  { tileIndex: 36, type: "CHANCE" },

  // Dark Blue – Peaks
  {
    tileIndex: 37,
    type: "PROPERTY",
    id: "makalu",
    name: "Makalu",
    price: 350,
    baseRent: 35,
    houseRent: [175, 500, 1100, 1300],
    hotelRent: 1500,
    houseBuildCost: 70,
    group: "peak",
  },
  { tileIndex: 38, type: "TAX", amount: 100 },
  {
    tileIndex: 39,
    type: "PROPERTY",
    id: "everest",
    name: "Everest",
    price: 400,
    baseRent: 50,
    houseRent: [200, 600, 1400, 1700],
    hotelRent: 2000,
    houseBuildCost: 80,
    group: "peak",
  },
];
